### ISSUE TITLE
Manual ffmpeg installation for FB360 spatial workstation encoder

### ISSUE THREAD

**Issue by JFB76** [sy1vain/homebrew-ffmpeg#1]
Hi, 

  I followed all instructions, but i got this error message:

ERROR: libmp3lame >= 3.98.3 not found

**Comment by sy1vain** [comment]
Which instructions did you follow? For me this installs fine.

Note: I only made this for one project which is not running anymore, so minimal support.

**Comment by JFB76** [comment]
Finally everything seems to work fine... Thanks
